# Generated by Django 3.1.7 on 2021-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=128, verbose_name='отчество'),
        ),
    ]
